### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by BertVerhees** [nedap/archie#46]
Hi  Pieter,

I found a small typo in the file OperatorKind.java. The "ge" is wrongly defined.
Thought you wanted to know this.

best regards
Bert Verhees

**Comment by pieterbos** [comment]
Hello Bert,

Thanks for reporting the issue. 

In OperatorKind.java ge is defined as:

```ge(">=", "≥")```

Which looks good to me. The ANTLR grammar does not yet include the UTF8 symbolic form ≥ so that will not parse, but that does not cause problems. Could you explain what is wrong with it?

**Comment by BertVerhees** [comment]
I am really sorry, I see that you repaired it four months ago (it was the "le", I must have an old version on my computer. I automatically update my local github-repositories, but this must have been missed for quite some times.

Sorry again, have a nice holiday.

**Comment by pieterbos** [comment]
No problem - still thanks for reporting!
