### ISSUE TITLE
parameter not used

### ISSUE THREAD

**Issue by ghost** [nedap/archie#69]
Hi Pieter, in the aom-class Archetype is function:
public ArchetypeTerm getTerm(CObject object, String code, String language) {
        return getTerminology().getTermDefinition(language, code);
    }

The parameter CObject object is not used, that does not seem right, is that an error?

**Comment by BertVerhees** [comment]
Sorry for being on the wrong archie version. And sorry that I did not know that unused parameters are regarded as good programming style in Java. Nice product you wrote, and every programming-ecosystem has its weaknesses, that is not your fault

**Comment by pieterbos** [comment]
Well it's not a flaw, but a design choice. To retrieve an archetype term for some types of archetypes you need either the cobject or the path of the cobject. Check the AOM 2 specification about component_terminologies  of the archetype terminology of OPERATIONAL_TEMPLATE on why and when this is required. So I required it for all archetypes. This choice means code anyone writes to get a term will work against all forms of archetypes - source form, flattened or operational templates. The alternative is messy code, with lots of instanceof calls to determine the right method to call, plus mistakes when people don't realize why they have to do this.
You can of course manually access the terminology :)
